export interface ProjectModel {
	AspectRatioId: string | null,
	AspectRatioName: string | null,
	ConnectionId: string | null,
	DateCreated: string | null,
	DateLastAccessed: string | null,
	DateStarted: string | null,
	Description: string | null,
	FileCount: string | null,
	FollowMeDto: string | null,
	GuestAccessCode: string | null,
	GuestAccessCodeCreatedDateTime: string | null,
	IsGuestModeEnabled: string | null,
	ManagerUserID: string | null,
	ManagerUserName: string | null,
	Name: string,
	ParticipantCount: number,
	ProductID: string | null,
	ProjectID: string | null,
	UserCount: number,
	UserHasAccess: string | null,
	UserId: string | null,
	WorkspaceCount: string | null
}
